export const stateCodes = [
  { state: "Alabama", code: 01 },
  { state: "Alaska", code: 01 },
  { state: "Arizona", code: 01 },
  { state: "Arkansas", code: 01 },
  { state: "California", code: 01 },
  { state: "Colorado", code: 01 },
  { state: "Connecticut", code: 01 },
  { state: "Delaware", code: 01 },
  { state: "District of Columbia", code: 01 },
  { state: "Florida", code: 01 },
  { state: "Georgia", code: 01 },
  { state: "Hawaii", code: 01 },
  { state: "xxxxxxx", code: 01 },
  { state: "xxxxxxx", code: 01 },
  { state: "xxxxxxx", code: 01 },
  { state: "xxxxxxx", code: 01 },
  { state: "xxxxxxx", code: 01 },
  { state: "xxxxxxx", code: 01 },
  { state: "xxxxxxx", code: 01 },
  { state: "xxxxxxx", code: 01 },
  { state: "xxxxxxx", code: 01 },
  { state: "xxxxxxx", code: 01 },
  { state: "xxxxxxx", code: 01 },
  { state: "xxxxxxx", code: 01 },
  { state: "xxxxxxx", code: 01 },
  { state: "xxxxxxx", code: 01 },
  { state: "xxxxxxx", code: 01 },
  { state: "xxxxxxx", code: 01 },
  { state: "xxxxxxx", code: 01 },
  { state: "xxxxxxx", code: 01 },
  { state: "xxxxxxx", code: 01 },
  { state: "xxxxxxx", code: 01 },
];
